"""new fields in user model

Revision ID: 791adce95708
Revises: 1710db3e9d96
Create Date: 2020-03-21 19:59:29.027887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '791adce95708'
down_revision = '1710db3e9d96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
